### ISSUE TITLE
Distribute on rubygems.org

### ISSUE THREAD

**Issue by kdeldycke** [rhass/kitchen-scaleway#1]
Any plan to publish kitchen-scaleway on rubygems.org ? :)

**Comment by moul** [comment]
:+1:

**Comment by edouardb** [comment]
:+1:

**Comment by aimxhaisse** [comment]
:+1:

**Comment by rhass-r7** [comment]
Wow! I didn't realize people had found this yet! 

I do plan to publish it, but I was going to get an omnitruck instance running on heroku first with some omnibus builds available via S3 for all the different OS flavors. Without omnitruck and omnibus builds, kitchen is less fun, as you need to pre-build Chef and manually install it first before kitchen can do anything once the instance it up. 

Nevertheless, I can publish the gem today.

I have a Kanban board on Trello which reflects the state of the overall project, and given I am doing this in my limited spare time I am hoping to get as many people helping out as I can.

https://trello.com/b/HWMrx3mT/chef-arm

Let me know if any of you are interested in any way.

**Comment by rhass** [comment]
Published the gem. It is now discoverable via, `kitchen driver discover`

**Comment by kdeldycke** [comment]
Wow, that was fast. Thanks @rhass ! :smiley:
